//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _301225212HosseinTehrani_Ass4
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerAddress
    {
        public string AddressType { get; set; }
        public string ModifedDate { get; set; }
        public int CustomerID { get; set; }
        public int AddressID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Address Address { get; set; }

        public override string ToString()
        {
            return CustomerID.ToString();
        }
    }
}
